<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <title>Анализатор страниц</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Анализатор страниц</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Сайты</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <main class="border rounded-3 bg-light container">
    <h1 class="display-3">Анализатор страниц</h1>
    <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
    <form>
      <input type="text" class="form-control form-control-lg" placeholder="https://www.example.com" name="url">
      <button type="submit" class="btn btn-lg btn-primary text-uppercase">Проверить</button>
    </form>
  </main>
  <footer class="border-top py-3 text-center position-fixed bottom-0 start-0 end-0">
    <a href="#">Hexlet</a>
  </footer>
</body>
</html>
