<?php
 $class = $valid ? '': ' is-invalid';
 $success = $messages['success'] ?? [];
 $error = $messages['error'] ?? [];
?>

<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <title>Анализатор страниц</title>
</head>
<body class="d-flex flex-column justify-content-between min-vh-100">
  <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/urls">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <?php foreach ($success as $message): ?>
      <div class="alert alert-success" role="alert">
        <?=$message?>
      </div>
    <?php endforeach; ?>

    <?php foreach ($error as $message): ?>
      <div class="alert alert-danger" role="alert">
        <?=$message?>
      </div>
    <?php endforeach; ?>

    <div class="container-lg">
      <div class="row justify-content-center">
        <main class="border rounded-3 bg-light col-11 col-xl-8 mt-3 p-5">
          <h1 class="display-3">Анализатор страниц</h1>
          <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
          <form class="row g-5" action='/urls' method='post'>
            <div class="col-12 col-lg-8 has-validation">
              <input 
                type="text" 
                class="form-control form-control-lg<?=$class?>" 
                placeholder="https://www.example.com" 
                name="url[name]"
                value="<?=$name?>"
              >
              <div class="invalid-feedback">
                Некорректный URL
              </div>
            </div>
            <div class="col-12 col-lg-4">
              <input 
                type="submit" 
                class="btn btn-lg btn-primary text-uppercase px-5 w-100"
                value="Проверить"
              >
            </div>
          </form>
        </main>
      </div>
    </div>
  </div>
  <footer class="border-top py-3 text-center mt-5">
    <a href="#">Hexlet</a>
  </footer>
</body>
</html>
